use std::collections::BTreeSet;

use cadrum::{Boolean, CurveGeometryKind, DVec3, ProfileOrient, Solid, SurfaceGeometryKind, Tessellation, TopologyKind, TopologyQueryOptions, TopologyRelationKind};

#[test]
fn cube_topology_snapshot_is_bidirectionally_consistent() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let topology = cube.topology_snapshot().expect("query cube topology");

	assert_eq!(topology.face_ids().len(), 6);
	assert_eq!(topology.edge_ids().len(), 12);
	assert_eq!(topology.vertex_ids().len(), 8);
	for face in 0..topology.face_ids().len() as u32 {
		let edges = topology.face_edges(face).expect("face adjacency");
		assert_eq!(edges.len(), 4);
		for edge in edges {
			assert!(topology.edge_faces(*edge).expect("edge adjacency").contains(&face));
		}
	}
	for edge in 0..topology.edge_ids().len() as u32 {
		assert_eq!(topology.edge_faces(edge).expect("edge adjacency").len(), 2);
	}
}

#[test]
fn topology_snapshot_batches_occurrences_adjacency_and_query_facts() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let topology = cube.topology_snapshot_with_options(TopologyQueryOptions::MEASUREMENT).expect("query cube facts");

	for face in 0..6 {
		let facts = topology.face_facts(face).expect("face facts");
		assert_eq!(facts.token.ordinal, face);
		assert_eq!(facts.geometry, Some(SurfaceGeometryKind::Plane));
		assert!(facts.representative_point.expect("face point").into_iter().all(f64::is_finite));
		assert!(facts.normal.expect("face normal").into_iter().all(f64::is_finite));
		assert!((facts.area.expect("face area") - 100.0).abs() < 1.0e-8);
	}
	for edge in 0..12 {
		let facts = topology.edge_facts(edge).expect("edge facts");
		assert_eq!(facts.token.ordinal, edge);
		assert_eq!(facts.geometry, Some(CurveGeometryKind::Line));
		assert_eq!(facts.vertices.len(), 2);
		assert!(facts.outward_direction.expect("edge outward direction").into_iter().all(f64::is_finite));
		assert!(facts.manifold);
		assert!(!facts.seam);
		assert!((facts.length.expect("edge length") - 10.0).abs() < 1.0e-8);
	}
	for vertex in 0..8 {
		let facts = topology.vertex_facts(vertex).expect("vertex facts");
		assert_eq!(facts.token.ordinal, vertex);
		assert!(facts.point.expect("vertex point").into_iter().all(f64::is_finite));
	}
}

#[test]
fn topology_distance_returns_exact_witness_points_without_meshing() {
	let first = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let second = Solid::cube(DVec3::new(15.0, 0.0, 0.0), DVec3::new(25.0, 10.0, 10.0));
	let first_face = first.iter_face().enumerate().max_by(|(_, left), (_, right)| left.project(DVec3::new(10.0, 5.0, 5.0)).expect("project first face").0.x.total_cmp(&right.project(DVec3::new(10.0, 5.0, 5.0)).expect("project first face").0.x)).expect("first face").0 as u32;
	let second_face = second.iter_face().enumerate().min_by(|(_, left), (_, right)| left.project(DVec3::new(15.0, 5.0, 5.0)).expect("project second face").0.x.total_cmp(&right.project(DVec3::new(15.0, 5.0, 5.0)).expect("project second face").0.x)).expect("second face").0 as u32;
	let distance = first.topology_distance(cadrum::ResultTopology { kind: TopologyKind::Face, index: first_face }, &second, cadrum::ResultTopology { kind: TopologyKind::Face, index: second_face }).expect("face distance");
	assert!((distance.distance - 5.0).abs() < 1.0e-9);
	assert!((distance.first_point.x - 10.0).abs() < 1.0e-9);
	assert!((distance.second_point.x - 15.0).abs() < 1.0e-9);
}

#[test]
fn fillet_reports_edge_generated_faces_and_complete_entity_kinds() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let edge = cube.iter_edge().next().expect("cube edge");
	let filleted = cube.fillet_edges(1.0, [edge]).expect("fillet cube edge");
	let history = filleted.topology_history();

	assert!(history.relations().iter().any(|relation| { relation.result.kind == TopologyKind::Face && relation.relation == TopologyRelationKind::Generated && relation.source.kind == TopologyKind::Edge }), "fillet transition face must be identified as generated by an input edge");
	assert!(history.relations().iter().any(|relation| relation.result.kind == TopologyKind::Edge));
	assert!(history.relations().iter().any(|relation| relation.result.kind == TopologyKind::Vertex));

	let topology = filleted.topology_snapshot().expect("fillet topology");
	for relation in history.relations() {
		let count = match relation.result.kind {
			TopologyKind::Face => topology.face_ids().len(),
			TopologyKind::Edge => topology.edge_ids().len(),
			TopologyKind::Vertex => topology.vertex_ids().len(),
		};
		assert!((relation.result.index as usize) < count);
	}
}

#[test]
fn extrusion_reports_profile_generated_caps_sides_edges_and_vertices() {
	let profile = cadrum::Edge::polygon(&[DVec3::new(-5.0, -5.0, 0.0), DVec3::new(5.0, -5.0, 0.0), DVec3::new(5.0, 5.0, 0.0), DVec3::new(-5.0, 5.0, 0.0)]).expect("profile");
	let extrusion = Solid::extrude(&profile, DVec3::Z * 10.0).expect("extrude");
	let history = extrusion.topology_history();
	assert!(history.unresolved().is_empty(), "unresolved: {:?}; relations: {:?}", history.unresolved(), history.relations());
	assert!(history.relations().iter().any(|relation| { relation.result.kind == TopologyKind::Face && relation.relation == TopologyRelationKind::Generated && relation.source.kind == TopologyKind::Edge }));
	assert!(history.relations().iter().any(|relation| relation.result.kind == TopologyKind::Edge));
	assert!(history.relations().iter().any(|relation| relation.result.kind == TopologyKind::Vertex));
}

#[test]
fn sweep_reports_profile_generated_topology() {
	let profile = cadrum::Edge::polygon(&[DVec3::new(-2.0, -2.0, 0.0), DVec3::new(2.0, -2.0, 0.0), DVec3::new(2.0, 2.0, 0.0), DVec3::new(-2.0, 2.0, 0.0)]).expect("profile");
	let spine = cadrum::Edge::line(DVec3::ZERO, DVec3::Z * 10.0).expect("spine");
	let swept = Solid::sweep(&profile, [&spine], ProfileOrient::Fixed).expect("sweep");
	assert!(swept.topology_history().relations().iter().any(|relation| { relation.result.kind == TopologyKind::Face && relation.relation == TopologyRelationKind::Generated && relation.source.kind == TopologyKind::Edge }));
}

#[test]
fn loft_reports_complete_section_namespaced_topology() {
	let lower = cadrum::Edge::polygon(&[DVec3::new(-3.0, -2.0, 0.0), DVec3::new(3.0, -2.0, 0.0), DVec3::new(3.0, 2.0, 0.0), DVec3::new(-3.0, 2.0, 0.0)]).expect("lower section");
	let upper = lower.iter().map(|edge| edge.shared_copy().translate(DVec3::new(0.5, 0.5, 8.0))).collect::<Vec<_>>();
	let loft = Solid::loft([lower.iter(), upper.iter()], false).expect("loft");
	let history = loft.topology_history();
	assert!(history.unresolved().is_empty(), "{history:?}");
	let topology = loft.topology_snapshot().expect("loft topology");
	for kind in [TopologyKind::Face, TopologyKind::Edge, TopologyKind::Vertex] {
		let expected = match kind {
			TopologyKind::Face => topology.face_ids().len(),
			TopologyKind::Edge => topology.edge_ids().len(),
			TopologyKind::Vertex => topology.vertex_ids().len(),
		};
		assert!((0..expected as u32).all(|index| history.relations().iter().any(|relation| relation.result.kind == kind && relation.result.index == index)));
	}
	assert_eq!(history.relations().iter().map(|relation| relation.source.operand).collect::<BTreeSet<_>>(), BTreeSet::from([0, 1]));
}

#[test]
fn decomposed_boolean_history_is_result_local_and_operand_aware() {
	let left = Solid::cube(DVec3::ZERO, DVec3::splat(1.0));
	let right = Solid::cube(DVec3::ZERO, DVec3::splat(1.0)).translate(DVec3::X * 4.0);
	let results = (Boolean::from(&left) + Boolean::from(&right)).build_vec().expect("disjoint union");
	assert_eq!(results.len(), 2);

	for result in results {
		let topology = result.topology_snapshot().expect("result topology");
		let history = result.topology_history();
		assert!(!history.relations().is_empty());
		for relation in history.relations() {
			let count = match relation.result.kind {
				TopologyKind::Face => topology.face_ids().len(),
				TopologyKind::Edge => topology.edge_ids().len(),
				TopologyKind::Vertex => topology.vertex_ids().len(),
			};
			assert!((relation.result.index as usize) < count, "sibling result relation leaked into this solid");
			assert!(relation.source.operand < 2);
		}
	}
}

#[test]
fn rigid_location_preserves_topology_tokens() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let original = cube.topology_snapshot().expect("query original topology");
	let located = cube.located(DVec3::Z, std::f64::consts::FRAC_PI_2, DVec3::X * 20.0);
	let transformed = located.topology_snapshot().expect("query located topology");

	assert_eq!(transformed.face_ids(), original.face_ids());
	assert_eq!(transformed.edge_ids(), original.edge_ids());
	let bounds = located.bounding_box();
	assert!(bounds[0].distance(DVec3::new(10.0, 0.0, 0.0)) < 1.0e-6);
	assert!(bounds[1].distance(DVec3::new(20.0, 10.0, 10.0)) < 1.0e-6);
}

#[test]
fn scale_and_mirror_return_complete_topology_correspondence() {
	let scaled = Solid::cube(DVec3::ZERO, DVec3::splat(10.0)).scale(DVec3::ZERO, 2.0);
	let scaled_topology = scaled.topology_snapshot().expect("scaled topology");
	assert!(scaled.topology_history().unresolved().is_empty());
	assert_eq!(scaled.topology_history().relations().len(), scaled_topology.face_ids().len() + scaled_topology.edge_ids().len() + scaled_topology.vertex_ids().len());

	let mirrored = scaled.mirror(DVec3::ZERO, DVec3::X);
	let mirrored_topology = mirrored.topology_snapshot().expect("mirrored topology");
	assert!(mirrored.topology_history().unresolved().is_empty());
	assert_eq!(mirrored.topology_history().relations().len(), mirrored_topology.face_ids().len() + mirrored_topology.edge_ids().len() + mirrored_topology.vertex_ids().len());
}

#[test]
fn explicit_deep_copy_returns_a_complete_ordinal_map() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let source = cube.topology_snapshot().expect("source topology");
	let copied = cube.deep_copy_with_map().expect("deep copy");
	let target = copied.topology_snapshot().expect("copied topology");

	assert_ne!(source.face_ids(), target.face_ids());
	assert_eq!(copied.topology_history().unresolved(), []);
	assert_eq!(copied.topology_history().relations().len(), source.face_ids().len() + source.edge_ids().len() + source.vertex_ids().len());
}

#[test]
fn shared_face_correspondence_includes_location_and_excludes_deep_copies() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let shared = cube.shared_copy();
	let moved = cube.located(DVec3::Z, 0.0, DVec3::X * 20.0);
	let copied = cube.deep_copy_with_map().expect("deep copy");

	assert_eq!(cube.shared_face_indices(&shared), (0..6).map(|index| (index, index)).collect::<Vec<_>>());
	assert!(cube.shared_face_indices(&moved).is_empty());
	assert!(cube.shared_face_indices(&copied).is_empty());
}

#[test]
fn keyed_mesh_chunks_cover_faces_and_ordered_edges() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let chunks = Solid::mesh_chunks([&cube], Tessellation::default()).expect("chunked mesh");
	assert_eq!(chunks.faces.len(), 6);
	assert_eq!(chunks.edges.len(), 12);
	for (index, face) in chunks.faces.iter().enumerate() {
		assert_eq!(face.face_index, index as u32);
		assert_eq!(face.vertices.len(), face.normals.len());
		assert!(!face.indices.is_empty());
		assert!(face.indices.iter().all(|vertex| (*vertex as usize) < face.vertices.len()));
	}
	for (index, edge) in chunks.edges.iter().enumerate() {
		assert_eq!(edge.edge_index, index as u32);
		assert!(edge.points.len() >= 2);
	}
	let selected = cube.mesh_face_chunks(&[1, 4], Tessellation::default()).expect("selected faces");
	assert_eq!(selected.iter().map(|chunk| chunk.face_index).collect::<Vec<_>>(), [1, 4]);
}

#[test]
fn surface_and_edge_presentation_can_be_requested_independently() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let options = Tessellation { include_edges: false, ..Tessellation::default() };
	let surfaces = Solid::mesh_chunks([&cube], options).expect("surface chunks");
	assert_eq!(surfaces.faces.len(), 6);
	assert!(surfaces.edges.is_empty());

	let edges = cube.edge_polyline_chunks(options).expect("edge chunks");
	assert_eq!(edges.len(), 12);
	assert!(edges.iter().all(|edge| edge.points.len() >= 2));
}

#[test]
fn exact_validation_accepts_primitive_blend_and_boolean_results() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let filleted = cube.fillet_edges(1.0, [cube.iter_edge().next().expect("edge")]).expect("fillet");
	let tool = Solid::cylinder(2.0, DVec3::Z * 10.0).translate(DVec3::new(5.0, 5.0, 0.0));
	let cut = (Boolean::from(&filleted) - Boolean::from(&tool)).build_vec().expect("cut");

	for solid in std::iter::once(&cube).chain(std::iter::once(&filleted)).chain(cut.iter()) {
		let report = solid.validate().expect("validate exact solid");
		assert!(report.valid, "invalid report: {report:?}");
		assert_eq!(report.invalid_faces, 0);
		assert_eq!(report.invalid_edges, 0);
		assert_eq!(report.invalid_vertices, 0);
	}
}
