use cadrum::{Boolean, DVec3, Solid, TopologyKind, TopologyRelationKind};

#[test]
fn cube_topology_snapshot_is_bidirectionally_consistent() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let topology = cube.topology_snapshot().expect("query cube topology");

	assert_eq!(topology.face_ids().len(), 6);
	assert_eq!(topology.edge_ids().len(), 12);
	assert_eq!(topology.vertex_ids().len(), 8);
	for face in 0..topology.face_ids().len() as u32 {
		let edges = topology.face_edges(face).expect("face adjacency");
		assert_eq!(edges.len(), 4);
		for edge in edges {
			assert!(topology.edge_faces(*edge).expect("edge adjacency").contains(&face));
		}
	}
	for edge in 0..topology.edge_ids().len() as u32 {
		assert_eq!(topology.edge_faces(edge).expect("edge adjacency").len(), 2);
	}
}

#[test]
fn fillet_reports_edge_generated_faces_and_complete_entity_kinds() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let edge = cube.iter_edge().next().expect("cube edge");
	let filleted = cube.fillet_edges(1.0, [edge]).expect("fillet cube edge");
	let history = filleted.topology_history();

	assert!(history.relations().iter().any(|relation| { relation.result.kind == TopologyKind::Face && relation.relation == TopologyRelationKind::Generated && relation.source.kind == TopologyKind::Edge }), "fillet transition face must be identified as generated by an input edge");
	assert!(history.relations().iter().any(|relation| relation.result.kind == TopologyKind::Edge));
	assert!(history.relations().iter().any(|relation| relation.result.kind == TopologyKind::Vertex));

	let topology = filleted.topology_snapshot().expect("fillet topology");
	for relation in history.relations() {
		let count = match relation.result.kind {
			TopologyKind::Face => topology.face_ids().len(),
			TopologyKind::Edge => topology.edge_ids().len(),
			TopologyKind::Vertex => topology.vertex_ids().len(),
		};
		assert!((relation.result.index as usize) < count);
	}
}

#[test]
fn decomposed_boolean_history_is_result_local_and_operand_aware() {
	let left = Solid::cube(DVec3::ZERO, DVec3::splat(1.0));
	let right = Solid::cube(DVec3::ZERO, DVec3::splat(1.0)).translate(DVec3::X * 4.0);
	let results = (Boolean::from(&left) + Boolean::from(&right)).build_vec().expect("disjoint union");
	assert_eq!(results.len(), 2);

	for result in results {
		let topology = result.topology_snapshot().expect("result topology");
		let history = result.topology_history();
		assert!(!history.relations().is_empty());
		for relation in history.relations() {
			let count = match relation.result.kind {
				TopologyKind::Face => topology.face_ids().len(),
				TopologyKind::Edge => topology.edge_ids().len(),
				TopologyKind::Vertex => topology.vertex_ids().len(),
			};
			assert!((relation.result.index as usize) < count, "sibling result relation leaked into this solid");
			assert!(relation.source.operand < 2);
		}
	}
}

#[test]
fn rigid_location_preserves_topology_tokens() {
	let cube = Solid::cube(DVec3::ZERO, DVec3::splat(10.0));
	let original = cube.topology_snapshot().expect("query original topology");
	let located = cube.located(DVec3::Z, std::f64::consts::FRAC_PI_2, DVec3::X * 20.0);
	let transformed = located.topology_snapshot().expect("query located topology");

	assert_eq!(transformed.face_ids(), original.face_ids());
	assert_eq!(transformed.edge_ids(), original.edge_ids());
	let bounds = located.bounding_box();
	assert!(bounds[0].distance(DVec3::new(10.0, 0.0, 0.0)) < 1.0e-6);
	assert!(bounds[1].distance(DVec3::new(20.0, 10.0, 10.0)) < 1.0e-6);
}
